name: 'tpc_h_sample'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  tpc_h_sample:
    00_control:
      +schema: control
      +materialized: table
    02_staging:
      +schema: stage
      +materialized: view
    03_raw_vault:
      +schema: rdv
      +materialized: incremental
    04_business_vault:
      +schema: bdv
      +materialized: table
